# Don't print a new line at the start of the prompt
add_newline = true

format = """
$directory\
$username\
$hostname\
$shlvl\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$swift\
$terraform\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$lua\
$jobs\
$battery\
$time\
$status\
$character"""

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[Vim](bold green) "

[cmd_duration]
show_milliseconds = true

[directory]
truncation_length = 5
style = "underline bold cyan"
#format = "[﬌](bold cyan) [$path]($style)[$lock_symbol]($lock_style) "
format = "[](bold cyan)  [$path]($style)[$lock_symbol]($lock_style) "

[memory_usage]
disabled = false

[username]
show_always = true
style_user = "bold bright-green"
format = "[$user]($style) "

[hostname]
format = "[$hostname]($style) "

[package]
disabled = true

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}${version}( \($virtualenv\))]($style) '
